### ISSUE TITLE
Error: The prop value with an expression type of BindExpression could not be resolved.

### ISSUE THREAD

**Issue by marylychee** [jsx-eslint/eslint-plugin-jsx-a11y#384]
[https://github.com/evcohen/jsx-ast-utils/issues/33](https://github.com/evcohen/jsx-ast-utils/issues/33)

The dependencies need to be updated. Eslint fails.

```
Running tasks for *.js
   ✖ lint:eslint
     →     at Traverser.traverse (/Users/marylai/zena-web-app/node_modules/estraverse/estraverse.js:501:28)
🚫 lint:eslint found some errors. Please fix them and try committing again.
The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extract [as JSXExpressionContainer] (/Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173:11)
    at getValue (/Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:76:95
    at Array.some (native)
    at EventEmitter.JSXOpeningElement (/Users/marylai/zena-web-app/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:75:52)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/Users/marylai/zena-web-app/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/marylai/zena-web-app/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/marylai/zena-web-app/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/marylai/zena-web-app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/Users/marylai/zena-web-app/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Traverser.enter (/Users/marylai/zena-web-app/node_modules/eslint/lib/eslint.js:929:36)
    at Traverser.__execute (/Users/marylai/zena-web-app/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/Users/marylai/zena-web-app/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by jessebeach** [comment]
Fixed by updating to jsx-ast-utils@v2.2.1
